version: '3'

services:
  db:
    image: mysql:latest
    container_name: my-db
    restart: always
    env_file:
      - db.env
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql